### ISSUE TITLE
iOS 14 support?

### ISSUE THREAD

**Issue by robertybob** [RedenticDev/AppMore#1]
Hey! This was such an invaluable tweak to me on 13.5, will this be updated to work on iOS 14.3?

**Comment by RedenticDev** [comment]
Hey! It already works on iOS 14, I just double checked on my iPhone 7 on 14.3 :) next updates will target iOS 11/12 support and improvements

**Comment by robertybob** [comment]
Ah I see! When I go to install itin Zebra it warns me that it only works from 13.0 to 13.7, I presume this is something you can fix when pushing your next update? :)

**Comment by RedenticDev** [comment]
Yes but it's only a warning on the depiction saying it hasn't been tested yet so you can always try by yourself
